name: Lint

on:
    push:
      branches:
      - yuxuans/bot
    pull_request:
      branches:
      - yuxuans/bot

jobs:
    update_internal:
        runs-on: ubuntu-latest
        steps:
          - name: Fetch Internal repo
            uses: actions/checkout@v2
            with:
              repository: fairinternal/minecraft
              token: ${{ secrets.SNYXAN_REPO }}
          - name: Fix git
            run: |
              set -eux
              git fetch origin yuxuans/sync_test
              git checkout yuxuans/sync_test
          - name: Update droidlet submodule to latest
            run: |
              git submodule update --init
              git submodule update --remote --merge
              pushd droidlet
              commit_msg="[Droidlet Update] $(git show -s --format=%s)"
              popd
              git config --global user.email "yuxuans+bot@fb.com"
              git config --global user.name "Droidlet Bot"
              git add droidlet && git commit -m "$commit_msg" && git push
          